version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXTAUTH_URL=https://your-domain.com
      - NEXTAUTH_SECRET=your-secret-key
      - GITHUB_ID=your-github-client-id
      - GITHUB_SECRET=your-github-client-secret
      - NODE_ENV=production
    restart: unless-stopped 